region               = "us-east-1"
environment          = "prod"
email_templates_bucket = "email-templates-quintana-prod"
dynamodb_table_name   = "clients-prod"
sqs_queue_name        = "email-queue-prod"
